version: '3'
services:
    ingestproto:
        build: ./ingestproto
        image: gttingestproto
        #container_name: "ingestproto"
        environment:
            - FOO=bar
        volumes:
            - ${HOME}/Dev/code/gtt/ingestproto/:/code/test/:rw
            - ${HOME}/Dev/code/gtt/logs/:/code/logs/:rw
        ports:
            - 3000:3000
            - 9000:9000
        depends_on:
            - processhit

    processhit:
        build: ./processhit
        image: gttprocesshit
        #container_name: "processhit"
        environment:
            - FOO=bar
        volumes:
            - ${HOME}/Dev/code/gtt/processhit/:/code/publish/:rw
            - ${HOME}/Dev/code/gtt/logs/:/code/logs/:rw
        ports:
            - 3001:3001
        expose:
            - 8000
