version: '3'
services:
    ingestproto:
        build: ./ingestproto
        image: gttingestproto
        #container_name: "ingestproto"
        environment:
            - FOO=bar
        volumes:
            - ${HOME}/Dev/code/gtt/ingestproto/:/code/test/:rw
            - ${HOME}/Dev/code/gtt/logs/:/code/logs/:rw
        depends_on:
            - processhit

    processhit:
        build: ./processhit
        image: gttprocesshit
        environment:
            - FOO=bar
        volumes:
            - ${HOME}/Dev/code/gtt/processhit/:/code/publish/:rw
            - ${HOME}/Dev/code/gtt/logs/:/code/logs/:rw
        ports:
            - 8000:8000

    observatory-service:
        build: ./observatory  # path is relative to docker-compose.yml localtion
    volumes:
        - ${HOME}/Dev/code/gtt/observatory:/usr/src/app # mount point
    ports:
        - 5001:80  # host:container
